spin_manifest_version = 2

[application]
name = "rust"
version = "0.1.0"
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "rust"

[component.rust]
source = "target/wasm32-wasi/release/rust.wasm"
allowed_http_hosts = []
[component.rust.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
