spin_manifest_version = 2

[application]
name = "component"
version = "0.1.0"
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "rust"

[component.rust]
source = "../target/wasm32-wasi/debug/rust.wasm"

